services:
  - type: web
    name: n8n-app
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npx n8n start --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: $PORT  # 使用 Render 動態端口
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        generateValue: true
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: MySecurePass123  # 自訂強密碼
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-postgres
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-postgres
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-postgres
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-postgres
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-postgres
          property: password
      - key: DB_SQLITE_POOL_SIZE
        value: 5
      - key: N8N_RUNNERS_ENABLED
        value: true
      - key: N8N_TRUST_PROXY
        value: true
      - key: N8N_USER_MANAGEMENT_ENABLED
        value: false
    disks: []  # 無需 Disk，依賴 PostgreSQL
databases:
  - name: n8n-postgres
    databaseName: n8n
    plan: free
